### ISSUE TITLE
v0.8.1 Disabled apps

### ISSUE THREAD

**Issue by bilogic** [quaap/LaunchTime#71]
Hi,

When an app is disabled, it's icon disappears from the menus. This is correct and good.
However, when an app is enabled, the icon does not appear by itself. Possible to auto detect or have a manual option to refresh? Thank you.

**Comment by quaap** [comment]
This should be fixed version 8.1 (the latest release).  It's working in my tests.  What version do you have, and which device and android version?

**Comment by bilogic** [comment]
I'm on 0.8.1, Samsung S5 Android 6.0

**Comment by bilogic** [comment]
I just tested re-enabling on v0.8.2, the previously disabled apps still do not show. Any idea how I can help troubleshoot? Thanks.

**Comment by quaap** [comment]
Weird.  It was working on my Android 8.0 and 7.1 emulators, but not on earlier versions. I tracked it down to a typo on my part: I had registered to receive "android.intent.action.ACTION_PACKAGE_CHANGED" events instead of "android.intent.action.PACKAGE_CHANGED".  I guess later versions of Android "helpfully" automatically corrected it? Oh well.  This fix will be in the next version.

**Comment by bilogic** [comment]
Thanks! Looking forward to it.

**Comment by bilogic** [comment]
Hi,

Will you consider adding Disabling of an app to the pop up menu of LaunchTime? 
It is 1 thing I realized was a need after using the latest version (which was GREAT! btw) for a while.

My thinking is, since LaunchTime is an app launcher/manager, why not do everything that is possible with apps? I disable apps because many of them are required only when overseas. I don't want them taking up any resources except storage space.

Thank you.
